python "F:\SiteProject\DBUpdate\TWSE_ETF_Holding.py"
python "F:\SiteProject\DBUpdate\getStockListDaily.py"
python "F:\SiteProject\DBUpdate\TWSE_Actions_Daily.py"
python "F:\SiteProject\DBUpdate\TWSE_HistoricalPrice_Daily.py"
python "F:\SiteProject\DBUpdate\TWSE_IntradayIndex_Daily.py"